package com.quizplatform.controller;
import com.quizplatform.dao.*; import com.quizplatform.model.*; import com.quizplatform.service.*; import com.quizplatform.util.SessionAuth; import jakarta.servlet.http.*; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import java.util.*;
/** Handles browser requests and prepares data for the quiz platform's page templates. */
@Controller public class HomeController {
 private final AuthService auth;private final UserDao users;private final QuizDao quizzes;private final QuestionDao questions;private final AttemptDao attempts;private final QuizService quizService;
 public HomeController(AuthService a,UserDao u,QuizDao q,QuestionDao qs,AttemptDao at,QuizService service){auth=a;users=u;quizzes=q;questions=qs;attempts=at;quizService=service;}
 @GetMapping("/") public String home(Model m,HttpSession s){SessionAuth.addUser(m,s);m.addAttribute("quizzes",quizService.available());return "home";}
 @GetMapping("/register") public String register(){return "register";}
 @PostMapping("/register") public String register(@RequestParam String name,@RequestParam String email,@RequestParam String password,@RequestParam String role,Model m){try{auth.register(name,email,password,role);return "redirect:/login?registered";}catch(IllegalArgumentException e){m.addAttribute("error",e.getMessage());return "register";}}
 @GetMapping("/login") public String login(){return "login";}
 @PostMapping("/login") public String login(@RequestParam String email,@RequestParam String password,HttpSession s,Model m){try{s.setAttribute("user",auth.login(email,password));return "redirect:/dashboard";}catch(IllegalArgumentException e){m.addAttribute("error",e.getMessage());return "login";}}
 @PostMapping("/logout") public String logout(HttpSession s){s.invalidate();return "redirect:/";}
 /** Selects a dashboard by account subtype and adds the matching user/quiz data. */
 @GetMapping("/dashboard") public String dashboard(HttpSession s,Model m){User u=SessionAuth.user(s);if(u==null)return "redirect:/login";m.addAttribute("currentUser",u);if(u instanceof Admin){m.addAttribute("users",users.findAll());m.addAttribute("quizzes",quizzes.all());m.addAttribute("reports",attempts.report());return "admin";}if(u instanceof QuizCreator){m.addAttribute("quizzes",quizzes.byCreator(u.getId()));m.addAttribute("reports",attempts.forCreator(u.getId()));return "creator";}m.addAttribute("quizzes",quizService.available());m.addAttribute("attempts",attempts.byParticipant(u.getId()));return "participant";}
 @GetMapping("/quizzes") public String quizList(HttpSession s,Model m){if(SessionAuth.user(s)==null)return "redirect:/login";m.addAttribute("currentUser",SessionAuth.user(s));m.addAttribute("quizzes",quizService.available());return "quizzes";}
 @GetMapping("/creator/quizzes/new") public String createQuiz(HttpSession s,Model m){SessionAuth.require(s,"CREATOR");SessionAuth.addUser(m,s);return "quiz-form";}
 /** Validates a creator's quiz details, creates the quiz, and opens question management. */
 @PostMapping("/creator/quizzes") public String saveQuiz(@RequestParam String title,@RequestParam(required=false)String description,@RequestParam(defaultValue="20")int durationMinutes,HttpSession s,Model m){User u=SessionAuth.user(s);if(u==null)return "redirect:/login";if(!u.getRole().equals("CREATOR"))throw new SessionAuth.ForbiddenException();if(title.isBlank()||durationMinutes<1||durationMinutes>180){m.addAttribute("error","Enter a title and a duration between 1 and 180 minutes.");m.addAttribute("currentUser",u);return "quiz-form";}long id=quizzes.create(u.getId(),title.trim(),description==null?"":description.trim(),durationMinutes);return "redirect:/creator/quizzes/"+id+"/questions";}
 @GetMapping("/creator/quizzes/{id}/questions") public String manageQuestions(@PathVariable long id,HttpSession s,Model m){User u=SessionAuth.require(s,"CREATOR");Quiz q=quizzes.find(id).orElseThrow();if(q.getCreatorId()!=u.getId())throw new SessionAuth.ForbiddenException();m.addAttribute("currentUser",u);m.addAttribute("quiz",q);m.addAttribute("questions",questions.byQuiz(id));return "questions";}
 @GetMapping("/creator/quizzes/{id}/questions/new") public String newQuestion(@PathVariable long id,HttpSession s,Model m){User u=SessionAuth.require(s,"CREATOR");Quiz q=quizzes.find(id).orElseThrow();if(q.getCreatorId()!=u.getId())throw new SessionAuth.ForbiddenException();m.addAttribute("currentUser",u);m.addAttribute("quiz",q);return "question-form";}
 /** Validates question data, then inserts a new question or updates the supplied question ID. */
 @PostMapping("/creator/quizzes/{id}/questions") public String addQuestion(@PathVariable long id,@RequestParam(required=false)Long questionId,@RequestParam String text,@RequestParam String optionA,@RequestParam String optionB,@RequestParam String optionC,@RequestParam String optionD,@RequestParam String correctOption,@RequestParam(defaultValue="1")int points,HttpSession s){User u=SessionAuth.require(s,"CREATOR");Quiz q=quizzes.find(id).orElseThrow();if(q.getCreatorId()!=u.getId())throw new SessionAuth.ForbiddenException();if(text.isBlank()||optionA.isBlank()||optionB.isBlank()||optionC.isBlank()||optionD.isBlank()||!List.of("A","B","C","D").contains(correctOption)||points<1)throw new IllegalArgumentException("Complete every field and choose a valid answer.");if(questionId==null)questions.create(id,text,optionA,optionB,optionC,optionD,correctOption,points);else questions.update(questionId,id,text,optionA,optionB,optionC,optionD,correctOption,points);return "redirect:/creator/quizzes/"+id+"/questions";}
 @GetMapping("/creator/quizzes/{id}/questions/{qid}/edit") public String editQuestion(@PathVariable long id,@PathVariable long qid,HttpSession s,Model m){User u=SessionAuth.require(s,"CREATOR");Quiz q=quizzes.find(id).orElseThrow();if(q.getCreatorId()!=u.getId())throw new SessionAuth.ForbiddenException();m.addAttribute("currentUser",u);m.addAttribute("quiz",q);m.addAttribute("question",questions.find(qid).orElseThrow());return "question-form";}
 @PostMapping("/creator/quizzes/{id}/questions/{qid}/delete") public String deleteQuestion(@PathVariable long id,@PathVariable long qid,HttpSession s){User u=SessionAuth.require(s,"CREATOR");Quiz q=quizzes.find(id).orElseThrow();if(q.getCreatorId()!=u.getId())throw new SessionAuth.ForbiddenException();questions.delete(qid,id);return "redirect:/creator/quizzes/"+id+"/questions";}
 /** Changes publication state, preventing a quiz with no questions from being published. */
 @PostMapping("/creator/quizzes/{id}/publish") public String publish(@PathVariable long id,@RequestParam boolean published,HttpSession s){User u=SessionAuth.require(s,"CREATOR");Quiz q=quizzes.find(id).orElseThrow();if(q.getCreatorId()!=u.getId())throw new SessionAuth.ForbiddenException();if(published&&questions.byQuiz(id).isEmpty())throw new IllegalStateException("Add at least one question before publishing.");quizzes.update(id,u.getId(),q.getTitle(),q.getDescription(),q.getDurationMinutes(),published);return "redirect:/dashboard";}
 @PostMapping("/creator/quizzes/{id}/delete") public String deleteQuiz(@PathVariable long id,HttpSession s){User u=SessionAuth.require(s,"CREATOR");quizzes.delete(id,u.getId());return "redirect:/dashboard";}
 /** Starts a participant's timed attempt and redirects to its question page. */
 @GetMapping("/quizzes/{id}/start") public String start(@PathVariable long id,HttpSession s){User u=SessionAuth.require(s,"PARTICIPANT");long attempt=quizService.start(id,u.getId());s.setAttribute("attempt-"+attempt,"active");return "redirect:/attempts/"+attempt;}
 @GetMapping("/attempts/{id}") public String take(@PathVariable long id,HttpSession s,Model m){User u=SessionAuth.require(s,"PARTICIPANT");QuizAttempt a=attempts.find(id).filter(x->x.getParticipantId()==u.getId()&&x.getStatus().equals("IN_PROGRESS")).orElseThrow();m.addAttribute("currentUser",u);m.addAttribute("attempt",a);m.addAttribute("quiz",quizzes.find(a.getQuizId()).orElseThrow());m.addAttribute("questions",quizService.questions(a.getQuizId()));return "take-quiz";}
 /** Converts form keys such as q_12 into question IDs before asking the service to score them. */
 @PostMapping("/attempts/{id}/submit") public String submit(@PathVariable long id,@RequestParam Map<String,String> form,HttpSession s){User u=SessionAuth.require(s,"PARTICIPANT");Map<Long,String> answers=new HashMap<>();form.forEach((k,v)->{if(k.startsWith("q_"))try{answers.put(Long.parseLong(k.substring(2)),v);}catch(NumberFormatException ignored){}});quizService.submit(id,u.getId(),answers);return "redirect:/results/"+id;}
 /** Allows admins, the participant, or the quiz's creator to view the result. */
 @GetMapping("/results/{id}") public String result(@PathVariable long id,HttpSession s,Model m){User u=SessionAuth.user(s);if(u==null)return "redirect:/login";if(!u.getRole().equals("ADMIN")&&!attempts.find(id).filter(a->a.getParticipantId()==u.getId()||quizzes.find(a.getQuizId()).map(q->q.getCreatorId()==u.getId()).orElse(false)).isPresent())throw new SessionAuth.ForbiddenException();m.addAttribute("currentUser",u);m.addAttribute("result",attempts.result(id));return "result";}
 @GetMapping("/history") public String history(HttpSession s,Model m){User u=SessionAuth.require(s,"PARTICIPANT");m.addAttribute("currentUser",u);m.addAttribute("attempts",attempts.byParticipant(u.getId()));return "history";}
 @GetMapping("/admin/reports") public String reports(HttpSession s,Model m){User u=SessionAuth.require(s,"ADMIN");m.addAttribute("currentUser",u);m.addAttribute("reports",attempts.report());m.addAttribute("users",users.findAll());m.addAttribute("quizzes",quizzes.all());return "admin";}
}
